- name: Generate SSH key
  shell: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""

- name: Copy SSH key to all hosts
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    exclusive: True
