
  tasks:
  - name: Generate SSH key
    command: ssh-keygen -f ~/.ssh/id_rsa -N "" -t rsa
    args:
      creates: ~/.ssh/id_rsa

  - name: Copy SSH key to remote host
    authorized_key:
      user: "{{ ansible_user }}"
      key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
