- name: Install strongSwan
  apt: name=strongswan state=installed

- name: Configure strongSwan
  template:
    src: ipsec.conf.j2
    dest: /etc/ipsec.conf
    owner: root
    group: root
    mode: 0600

- name: Start strongSwan
  service:
    name: strongswan
    state: started
