  - name: Update package manager
    package_manager:
      update_cache: yes

  - name: Install required packages
    package:
      name:
      - ipsec-tools
      - rsync
      state: present
      
  - name: Set a hostname
    ansible.builtin.hostname:
      name: rpi-test1
